### ISSUE TITLE
refactor: remove custom styles

### ISSUE THREAD

**Issue by shailscript** [umangcodes/users-management-crud-app#2]
Custom CSS adds maintenance overhead over time. Unless you have a design system you're following, I won't recommend using custom CSS. An alternative is #1 

Try to minimise code in following files, or remove them entirely
- https://github.com/umangcodes/react-crud-1/blob/main/src/App.css
- https://github.com/umangcodes/react-crud-1/blob/main/src/index.css

**Comment by umangcodes** [comment]
Done. will be using MUI to upgrade this project.
