### ISSUE TITLE
refactor: rename repository

### ISSUE THREAD

**Issue by shailscript** [umangcodes/users-management-crud-app#3]
Name it something user-friendly which gives an idea of the project. For example: `user-registration-ui` - just an example, you can do better.

Update readme with your approach to developing this project, live link, badges etc. Add credits to sources, if any.

**Comment by umangcodes** [comment]
Done.

**Comment by shailscript** [comment]
Update readme with your approach to developing this project, live link, badges etc. Add credits to sources, if any.
