### ISSUE TITLE
refactor: use local storage

### ISSUE THREAD

**Issue by shailscript** [umangcodes/users-management-crud-app#4]
Right now, when I come to your site I can add my details but it is only available for the session. Any edits I make to the other user's info are also available for the session only. You can use `localstorage` to persist changes/data. Eventually, you can move to a service like firebase for instance.

Also, investigate using repository pattern so you can move to firebase-like service in the future with minimal maintenance overhead.

**Comment by umangcodes** [comment]
Done. one thing about local storage is that it converts the data into strings so it's better to convert it into JSON string and while retrieving data, parse it back into json object.


Feature added!

**Comment by shailscript** [comment]
Please add ref to commits or PR when closing an issue here!
